"""学术海报渲染：可读性优化、小圆角卡片、阴影层次、紧凑填充."""

from __future__ import annotations

import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from poster_agent.models.trees import PosterNode
from poster_agent.render.image_fit import is_generated_visual, natural_fit_height, smart_fit_image
from poster_agent.render.text_layout import text_width, truncate_to_width, wrap_to_width
from poster_agent.render.text_utils import format_body

THEME = {
    "header_bg": (32, 58, 110),
    "header_fg": (255, 255, 255),
    "header_sub": (190, 205, 230),
    "canvas_bg": (235, 238, 242),
    "section_bg": (255, 255, 255),
    "section_border": (175, 192, 218),
    "section_bar": (41, 84, 144),
    "body_text": (30, 36, 48),
    "shadow": (195, 202, 214),
}

CARD_RADIUS = 4
BAR_RADIUS = 4
SECTION_INNER_PAD = 20
LINE_SPACING = 10
PARA_SPACING = 12
SHADOW_OFFSET = (2, 3)


class PosterRenderer:
    CANVAS_W = 2400
    CANVAS_H = 3600

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.paper_title = "Academic Poster"
        self.authors = ""

    def render_png(
        self,
        tree: PosterNode,
        name: str,
        paper_title: str | None = None,
        authors: str | None = None,
    ) -> Path:
        if paper_title:
            self.paper_title = paper_title
        if authors:
            self.authors = format_body(authors)
        img = Image.new("RGB", (self.CANVAS_W, self.CANVAS_H), THEME["canvas_bg"])
        draw = ImageDraw.Draw(img)
        self._draw_header(draw)
        for node in _collect_leaves(tree):
            self._draw_section(draw, img, node)
        self._draw_footer(draw)
        out = self.output_dir / f"{name}.png"
        img.save(out, quality=96)
        return out

    def render_pptx(
        self,
        tree: PosterNode,
        name: str,
        paper_title: str | None = None,
        authors: str | None = None,
    ) -> Path:
        from pptx import Presentation

        png = self.render_png(tree, f"{name}_tmp", paper_title, authors)
        prs = Presentation()
        prs.slide_width = 9144000 * 24 // 10
        prs.slide_height = 9144000 * 36 // 10
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        slide.shapes.add_picture(str(png), 0, 0, width=prs.slide_width, height=prs.slide_height)
        png.unlink(missing_ok=True)
        out = self.output_dir / f"{name}.pptx"
        prs.save(out)
        return out

    def _draw_header(self, draw: ImageDraw.ImageDraw) -> None:
        h = 268
        draw.rectangle([0, 0, self.CANVAS_W, h], fill=THEME["header_bg"])
        draw.rectangle([0, h - 4, self.CANVAS_W, h], fill=(55, 90, 150))

        ft = _load_font(54, bold=True)
        fa = _load_font(24)

        title = self.paper_title
        max_title_w = self.CANVAS_W - 160
        title_lines = wrap_to_width(title, ft, max_title_w)
        if len(title_lines) > 2:
            title_lines = title_lines[:2]
            title_lines[-1] = truncate_to_width(title_lines[-1], ft, max_title_w)
        y = 44
        for line in title_lines:
            tw = text_width(line, ft)
            draw.text(((self.CANVAS_W - tw) // 2, y), line, fill=THEME["header_fg"], font=ft)
            y += 60

        sub = self.authors or "Auto-generated Academic Poster | Multi-agent System"
        sub_lines = wrap_to_width(sub, fa, max_title_w)
        sub_line = sub_lines[0] if sub_lines else sub
        if len(sub_lines) > 1:
            sub_line = truncate_to_width(sub_line, fa, max_title_w)
        sw = text_width(sub_line, fa)
        draw.text(((self.CANVAS_W - sw) // 2, y + 6), sub_line, fill=THEME["header_sub"], font=fa)

        draw.rounded_rectangle([40, 40, 116, 116], radius=4, outline=(120, 150, 200), width=2)
        draw.text((58, 68), "LOGO", fill=THEME["header_sub"], font=_load_font(22))

    def _draw_footer(self, draw: ImageDraw.ImageDraw) -> None:
        y = self.CANVAS_H - 46
        draw.rectangle([0, y, self.CANVAS_W, self.CANVAS_H], fill=THEME["header_bg"])
        msg = "Generated by Hierarchical Multi-agent Poster System"
        fw = _text_width(msg, _load_font(18))
        draw.text(((self.CANVAS_W - fw) // 2, y + 12), msg, fill=THEME["header_sub"], font=_load_font(18))

    def _draw_section(self, draw: ImageDraw.ImageDraw, img: Image.Image, node: PosterNode) -> None:
        r = node.rect
        ox, oy, ow, oh = r.x, r.y, r.width, r.height

        sx, sy = SHADOW_OFFSET
        draw.rounded_rectangle(
            [ox + sx, oy + sy, ox + ow + sx, oy + oh + sy],
            radius=CARD_RADIUS,
            fill=THEME["shadow"],
        )
        draw.rounded_rectangle(
            [ox, oy, ox + ow, oy + oh],
            radius=CARD_RADIUS,
            fill=THEME["section_bg"],
            outline=THEME["section_border"],
            width=2,
        )

        title_font = node.font_size_title
        bar_h = max(title_font + 24, 48)
        bar_y1 = oy + SECTION_INNER_PAD
        bar_x0 = ox + SECTION_INNER_PAD
        bar_x1 = ox + ow - SECTION_INNER_PAD
        draw.rounded_rectangle(
            [bar_x0, bar_y1, bar_x1, bar_y1 + bar_h],
            radius=BAR_RADIUS,
            fill=THEME["section_bar"],
        )

        ft = _load_font(title_font, bold=True)
        section_title = node.title
        icon_size = max(int(title_font * 0.65), 22)
        bar_text_w = bar_x1 - bar_x0 - icon_size - 36
        while text_width(section_title, ft) > bar_text_w and title_font > 24:
            title_font -= 2
            ft = _load_font(title_font, bold=True)
        icon_y = bar_y1 + (bar_h - icon_size) // 2
        _draw_bar_icon(draw, bar_x0 + 12, icon_y, node.section_icon or "doc", icon_size)
        text_y = bar_y1 + (bar_h - title_font) // 2
        draw.text(
            (bar_x0 + icon_size + 22, text_y),
            truncate_to_width(section_title, ft, bar_text_w),
            fill=(255, 255, 255),
            font=ft,
        )

        content_top = bar_y1 + bar_h + SECTION_INNER_PAD
        content_box = (
            bar_x0,
            content_top,
            bar_x1,
            oy + oh - SECTION_INNER_PAD,
        )
        mode = node.layout_mode or "text_only"
        figures = _collect_figures(node)
        fb = _load_font(node.font_size_body)

        if mode == "figure_top" and figures:
            self._layout_figure_top(draw, img, node, content_box, figures, fb)
        elif mode == "side_by_side" and figures:
            self._layout_side_by_side(draw, img, node, content_box, figures, fb)
        elif mode == "figure_bottom" and figures:
            self._layout_figure_bottom(draw, img, node, content_box, figures, fb)
        elif mode == "text_dense":
            self._layout_text_dense(draw, node, content_box, fb)
        else:
            self._layout_text_only(draw, img, node, content_box, figures, fb)

    def _layout_figure_top(self, draw, img, node, box, figures, fb) -> None:
        x0, y0, x1, y1 = box
        w, total_h = x1 - x0, y1 - y0
        fig_h = self._figure_slot_height(figures, w, total_h, max_ratio=0.55)
        fig_bottom = self._paste_figures(img, figures, x0, y0, w, fig_h, draw, fit_contain=True)
        text_y = fig_bottom + 8
        text_h = max(y1 - text_y, 40)
        self._draw_text_block(
            draw, node, x0, text_y, w, text_h, fb,
            numbered=True, distribute=True,
        )

    def _layout_side_by_side(self, draw, img, node, box, figures, fb) -> None:
        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        text_w = int(w * 0.48)
        gap = 14
        fig_x = x0 + text_w + gap
        fig_w = x1 - fig_x
        self._draw_text_block(
            draw, node, x0, y0, text_w, h, fb,
            numbered=True, distribute=True,
        )
        self._paste_figures(img, figures, fig_x, y0, fig_w, h, draw, fill=True)

    def _layout_figure_bottom(self, draw, img, node, box, figures, fb) -> None:
        x0, y0, x1, y1 = box
        w, total_h = x1 - x0, y1 - y0
        fig_h = self._figure_slot_height(figures, w, total_h, max_ratio=0.42)
        text_h = total_h - fig_h - 10
        text_bottom = self._draw_text_block(
            draw, node, x0, y0, w, text_h, fb,
            numbered=True, distribute=True,
        )
        fig_y = text_bottom + 8
        fig_alloc = max(y1 - fig_y, int(w * 0.16))
        self._paste_figures(img, figures, x0, fig_y, w, fig_alloc, draw)

    def _layout_text_dense(self, draw, node, box, fb) -> None:
        x0, y0, x1, y1 = box
        self._draw_text_block(
            draw, node, x0, y0, x1 - x0, y1 - y0, fb,
            numbered=True, compact=True, distribute=True,
        )

    def _layout_text_only(self, draw, img, node, box, figures, fb) -> None:
        x0, y0, x1, y1 = box
        w, total_h = x1 - x0, y1 - y0
        if figures:
            fig_h = self._figure_slot_height(figures, w, total_h, max_ratio=0.40)
            text_h = total_h - fig_h - 10
            self._draw_text_block(
                draw, node, x0, y0, w, text_h, fb,
                numbered=True, distribute=True,
            )
            self._paste_figures(img, figures, x0, y0 + text_h + 10, w, fig_h, draw)
        else:
            self._draw_text_block(
                draw, node, x0, y0, w, total_h, fb,
                numbered=True, distribute=True,
            )

    def _figure_slot_height(self, figures: list[str], width: int, total_h: int, *, max_ratio: float) -> int:
        if not figures or width <= 0:
            return 0
        pad = 12
        inner_w = max(width - pad * 2, 40)
        n = min(len(figures), 2)
        sub_w = (inner_w - 10) // 2 if n >= 2 else inner_w
        natural = 0
        for fig in figures[:n]:
            try:
                from PIL import Image
                src = Image.open(fig)
                gen = is_generated_visual(fig)
                nh = natural_fit_height(src, sub_w, is_generated=gen)
                if gen and Path(fig).stem.lower().find("vis") >= 0:
                    nh = int(nh * 1.12)
                natural = max(natural, nh + pad * 2)
            except Exception:
                natural = max(natural, int(width * 0.28))
        cap = int(total_h * max_ratio)
        floor_h = int(width * 0.22)
        return max(floor_h, min(natural, cap, total_h - 100))

    def _measure_text_height(
        self,
        node: PosterNode,
        w: int,
        font,
        *,
        numbered: bool = False,
    ) -> int:
        line_h = font.size + LINE_SPACING
        lines = 0
        if node.summary:
            lines += len(wrap_to_width(format_body(node.summary), font, w))
        for i, bullet in enumerate(node.bullets):
            prefix = f"{i + 1}. " if numbered else ""
            lines += len(wrap_to_width(prefix + format_body(bullet), font, w - 16))
        return lines * line_h + (PARA_SPACING if node.summary and node.bullets else 0)

    def _draw_text_block(
        self,
        draw: ImageDraw.ImageDraw,
        node: PosterNode,
        x: int,
        y: int,
        w: int,
        h: int,
        font,
        *,
        numbered: bool = False,
        compact: bool = False,
        distribute: bool = False,
    ) -> int:
        lines: list[tuple[str, int]] = []
        summary = format_body(node.summary)
        if summary:
            for line in wrap_to_width(summary, font, w):
                lines.append((line, 0))
            lines.append(("", 0))

        for i, bullet in enumerate(node.bullets):
            text = format_body(bullet)
            prefix = f"{i + 1}. " if numbered else ""
            wrapped = wrap_to_width(prefix + text, font, w - 16)
            for j, line in enumerate(wrapped):
                lines.append((line, 16 if j > 0 else 0))

        if not lines:
            return y

        base_spacing = 6 if compact else LINE_SPACING
        line_h = font.size + base_spacing
        content_h = len(lines) * line_h
        extra = max(0, h - content_h)
        extra_spacing = 0
        if distribute and extra > 0 and len(lines) > 1:
            extra_spacing = min(extra // max(len(lines) - 1, 1), 18)
        line_h = font.size + base_spacing + extra_spacing

        cy = y
        bottom = y + h
        for line, indent in lines:
            if not line:
                cy += PARA_SPACING // 2
                continue
            if cy + line_h > bottom:
                break
            draw.text((x + indent, cy), line, fill=THEME["body_text"], font=font)
            cy += line_h
        return cy

    def _paste_figures(
        self,
        img: Image.Image,
        figures: list[str],
        x: int,
        y: int,
        w: int,
        h: int,
        draw: ImageDraw.ImageDraw,
        *,
        fill: bool = False,
        fit_contain: bool = False,
    ) -> int:
        if not figures or w <= 8 or h <= 8:
            return y
        pad = 6
        inner_x0 = x + pad
        inner_y0 = y + pad
        inner_w = w - pad * 2
        inner_h = h - pad * 2
        if inner_w <= 8 or inner_h <= 8:
            return y

        n = min(len(figures), 2)
        gap = 10
        use_h = inner_h
        if not fill:
            slot_h = self._figure_slot_height(figures, w, h + 120, max_ratio=1.0)
            use_h = min(inner_h, max(slot_h - pad * 2, int(inner_w * 0.16)))

        draw.rounded_rectangle(
            [inner_x0, inner_y0, inner_x0 + inner_w, inner_y0 + use_h],
            radius=CARD_RADIUS,
            outline=THEME["section_border"],
            width=1,
        )

        use_fill = fill and not fit_contain
        if n == 1:
            self._fit_image(
                img, figures[0], inner_x0, inner_y0, inner_w, use_h,
                fill=use_fill,
            )
        else:
            sub_w = (inner_w - gap) // 2
            tight = use_fill or use_h >= inner_h * 0.85
            self._fit_image(img, figures[0], inner_x0, inner_y0, sub_w, use_h, fill=tight and not fit_contain)
            self._fit_image(
                img, figures[1], inner_x0 + sub_w + gap, inner_y0, sub_w, use_h, fill=tight and not fit_contain
            )
        return inner_y0 + use_h + pad

    def _fit_image(
        self,
        canvas: Image.Image,
        path: str,
        x: int,
        y: int,
        w: int,
        h: int,
        *,
        fill: bool = False,
    ) -> None:
        try:
            if not Path(path).exists() or w <= 0 or h <= 0:
                return
            src = Image.open(path).convert("RGB")
            fitted = smart_fit_image(src, w, h, is_generated=is_generated_visual(path))
            canvas.paste(fitted, (x, y))
        except Exception as exc:
            import logging
            logging.getLogger(__name__).warning("fit_image failed %s: %s", path, exc)


def _fit_contain(img: Image.Image, tw: int, th: int) -> Image.Image:
    """等比缩放至区域内完整显示，浅底居中，不裁剪."""
    sw, sh = img.size
    scale = min(tw / sw, th / sh)
    nw, nh = max(1, int(sw * scale)), max(1, int(sh * scale))
    img = img.resize((nw, nh), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (tw, th), (252, 253, 255))
    canvas.paste(img, ((tw - nw) // 2, (th - nh) // 2))
    return canvas


def _cover_resize(img: Image.Image, tw: int, th: int) -> Image.Image:
    """等比放大并居中裁剪，填满区域无留白."""
    sw, sh = img.size
    scale = max(tw / sw, th / sh)
    nw, nh = int(sw * scale), int(sh * scale)
    img = img.resize((nw, nh), Image.Resampling.LANCZOS)
    left = (nw - tw) // 2
    top = (nh - th) // 2
    return img.crop((left, top, left + tw, top + th))


def _draw_bar_icon(draw: ImageDraw.ImageDraw, x: int, y: int, icon: str, size: int = 24) -> None:
    s = size
    draw.rounded_rectangle([x, y, x + s, y + s], radius=3, fill=(70, 110, 170))
    cx, cy = x + s // 2, y + s // 2
    scale = s / 24
    white = (255, 255, 255)
    if icon == "chart":
        draw.rectangle([cx - int(6 * scale), cy, cx - int(3 * scale), cy + int(5 * scale)], fill=white)
        draw.rectangle([cx - int(1 * scale), cy - int(4 * scale), cx + int(2 * scale), cy + int(5 * scale)], fill=white)
        draw.rectangle([cx + int(4 * scale), cy + int(1 * scale), cx + int(7 * scale), cy + int(5 * scale)], fill=white)
    elif icon == "gear":
        draw.ellipse([cx - int(6 * scale), cy - int(6 * scale), cx + int(6 * scale), cy + int(6 * scale)], outline=white, width=max(1, int(scale)))
        draw.ellipse([cx - int(2 * scale), cy - int(2 * scale), cx + int(2 * scale), cy + int(2 * scale)], fill=white)
    elif icon == "lightbulb":
        draw.ellipse([cx - int(5 * scale), cy - int(7 * scale), cx + int(5 * scale), cy + int(3 * scale)], fill=white)
        draw.rectangle([cx - int(3 * scale), cy + int(3 * scale), cx + int(3 * scale), cy + int(7 * scale)], fill=white)
    elif icon == "flag":
        draw.line([(cx - int(4 * scale), cy - int(7 * scale)), (cx - int(4 * scale), cy + int(7 * scale))], fill=white, width=max(1, int(2 * scale)))
        draw.polygon([
            (cx - int(4 * scale), cy - int(7 * scale)),
            (cx + int(7 * scale), cy - int(3 * scale)),
            (cx - int(4 * scale), cy + int(1 * scale)),
        ], fill=white)
    else:
        draw.rectangle([cx - int(6 * scale), cy - int(5 * scale), cx + int(6 * scale), cy + int(6 * scale)], outline=white, width=max(1, int(scale)))


def _collect_leaves(node: PosterNode) -> list[PosterNode]:
    if node.title in ("Poster Root", "Section Group"):
        return [c for ch in node.children for c in _collect_leaves(ch)]
    if not node.children:
        return [node]
    return [c for ch in node.children for c in _collect_leaves(ch)]


def _collect_figures(node: PosterNode) -> list[str]:
    paths: list[str] = []
    for p in node.image_paths:
        if p and Path(p).exists() and p not in paths:
            paths.append(p)
    if node.visual_path and Path(node.visual_path).exists() and node.visual_path not in paths:
        paths.insert(0, node.visual_path)
    elif node.image_path and Path(node.image_path).exists() and node.image_path not in paths:
        paths.append(node.image_path)
    return paths[:2]


def _load_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    names = ["msyhbd.ttc", "msyh.ttc", "simhei.ttf", "arialbd.ttf" if bold else "arial.ttf"]
    for name in names:
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _text_width(text: str, font) -> int:
    try:
        return int(font.getlength(text))
    except Exception:
        return len(text) * (font.size if hasattr(font, "size") else 12)


def _wrap_lines(text: str, width: int) -> list[str]:
    return textwrap.wrap(text, width=width) or [text]
